# Generated by Django 4.2.7 on 2024-01-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_email_paciente_emergency_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
