# Generated by Django 4.2.7 on 2024-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='modification_date',
            field=models.DateField(),
        ),
    ]
