# Generated by Django 4.2.7 on 2024-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
