# Generated by Django 4.2.7 on 2024-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hour_date',
            field=models.TimeField(default='00:00'),
        ),
    ]
