# Generated by Django 4.2.7 on 2024-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_roles_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='RolesUsuario',
        ),
    ]
